<a href="https://colab.research.google.com/github/truonghuynh210962/Python-on-the-way/blob/main/Soduku_Solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import itertools

In [2]:
set_of_nums = np.array([1,2,3,4,5,6,7,8,9])
sum_of_set = sum(set_of_nums)

In [3]:
def fill_rows():
  table = [[6,0,0,1,5,7,0,0,0],
           [3,0,0,2,0,4,0,9,0],
           [0,1,0,0,0,6,0,4,0],
           [2,6,0,0,1,0,8,0,3],
           [5,0,0,0,0,0,9,2,4],
           [0,0,3,9,0,0,0,0,5],
           [1,3,0,6,0,2,0,0,0],
           [9,4,6,8,3,1,7,0,0],
           [7,0,0,0,4,9,0,1,0]]
  rows = []
  rows_fill = []
  for i in set_of_nums:
    rows.append(table[i-1])
    mask = (np.isin(set_of_nums,table[i-1],invert=True))
    rows_fill.append(set_of_nums[mask])
  return rows,rows_fill
rows = fill_rows()[0]
row_fills = fill_rows()[1]

In [4]:
dict_rows = {}
for i in set_of_nums:
  dict_rows[i] = []
for key,value in dict_rows.items():
  permutations = list(itertools.permutations(row_fills[key-1]))
  for i_per in permutations:
    #print (i_per)
    row = fill_rows()[0][key-1]
    #print (row)
    i_per_arr = np.array(i_per)
    for j_per in i_per_arr:
      for i,j in enumerate(row):
        if j == 0:
          row[i] = j_per
          break
      i_per_arr = i_per_arr[np.isin(i_per_arr,j_per,invert=True)]
    dict_rows[key].append(list(row))

In [5]:
combin = []
for value in dict_rows.values():
  combin.append(list(value))

In [6]:
row13 = list(itertools.product(combin[0],combin[1],combin[2]))

In [7]:
sumblock = 0
sumblock_list = []
blocks = []
block_set_list = []
result13 = []
for i in row13: #change row to 1-3
  for j in [0,3,6]:
    for lines in i:
      #print (lines[j:j+3])
      sumblock += sum(lines[j:j+3])
      blocks+=lines[j:j+3]
    #print (blocks)
    # if sumblock != 45 or len(set(blocks)) !=9:
    #   break
    sumblock_list.append(sumblock)
    block_set_list.append(len(set(blocks)))
    sumblock = 0
    blocks = []
  #print (sumblock_list,block_set_list)
  if sumblock_list == [45,45,45] and block_set_list == [9,9,9]:
    #print (i)
    result13.append(i)
  sumblock_list = []
  block_set_list = []
del row13 #del varibale

In [8]:
row46 = list(itertools.product(combin[3],combin[4],combin[5]))

In [9]:
sumblock = 0
sumblock_list = []
blocks = []
block_set_list = []
result46 = [] #set result46 list
for i in row46: #change row to 4-6
  for j in [0,3,6]:
    for lines in i:
      #print (lines[j:j+3])
      sumblock += sum(lines[j:j+3])
      blocks+=lines[j:j+3]
    # if sumblock != 45 or len(set(blocks)) !=9:
    #   break
    sumblock_list.append(sumblock)
    block_set_list.append(len(set(blocks)))
    sumblock = 0
    blocks = []
  #print (sumblock_list,block_set_list)
  if sumblock_list == [45,45,45] and block_set_list == [9,9,9]:
    result46.append(i)
  sumblock_list = []
  block_set_list = []
del row46 #del varibale

In [10]:
row79 = list(itertools.product(combin[6],combin[7],combin[8]))

In [11]:
sumblock = 0
sumblock_list = []
blocks = []
block_set_list = []
result79 = []

for i in row79: #change row to 7-9
  for j in [0,3,6]:
    for lines in i:
      #print (lines[j:j+3])
      sumblock += sum(lines[j:j+3])
      blocks+=lines[j:j+3]
    sumblock_list.append(sumblock)
    block_set_list.append(len(set(blocks)))
    sumblock = 0
    blocks = []
  #print (sumblock_list,block_set_list)
  if sumblock_list == [45,45,45] and block_set_list == [9,9,9]:
    result79.append(i)
  sumblock_list = []
  block_set_list = []
del row79 #del varibale

In [12]:
result1_9 = list(itertools.product(result13,result46,result79))
print(len(result1_9))
for i in result1_9:
  if np.all(np.sum(np.array(i).reshape(9,9).T,axis=0) == 45) and np.all(np.array([len(set(j)) for j in np.array(i).reshape(9,9).T]) == 9):
    print (np.array(i).reshape(9,9))
    break
    del result1_9


7077888
[[6 9 4 1 5 7 2 3 8]
 [3 5 7 2 8 4 6 9 1]
 [8 1 2 3 9 6 5 4 7]
 [2 6 9 4 1 5 8 7 3]
 [5 8 1 7 6 3 9 2 4]
 [4 7 3 9 2 8 1 6 5]
 [1 3 5 6 7 2 4 8 9]
 [9 4 6 8 3 1 7 5 2]
 [7 2 8 5 4 9 3 1 6]]
